# Generated by Django 5.0.3 on 2024-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_title', models.CharField(max_length=255, verbose_name='Themes title')),
                ('themes_txt', models.TextField(verbose_name='themes context')),
            ],
            options={
                'verbose_name': 'Themes',
                'verbose_name_plural': 'Themes',
                'db_table': 'themes',
            },
        ),
    ]
